[package]
name = "oxdock-fs"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
mock-fs = []
embed = ["dep:rust-embed"]

[dependencies]
anyhow.workspace = true
rust-embed = { workspace = true, optional = true }
tempfile.workspace = true
tracing = { workspace = true }
