[package]
name = "oxdock-fs"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
mock-fs = []

[dependencies]
anyhow.workspace = true
oxdock-process.workspace = true
tempfile.workspace = true
