[package]
name = "oxdock-buildtime-macros"
description = "Placeholder crate"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
oxdock-core.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
tempfile.workspace = true

[dev-dependencies]
serial_test.workspace = true
