[package]
name = "oxdock-buildtime-macros"
description = "Placeholder crate"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
oxdock-core.workspace = true
oxdock-fs.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
tracing = { workspace = true }

[dev-dependencies]
oxdock-fs = { workspace = true, features = ["embed"] }
oxdock-process.workspace = true
serial_test.workspace = true
