[package]
name = "oxdock-buildtime-macros"
version = "0.1.0-alpha"
edition = "2024"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
oxdock-core.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
tempfile.workspace = true

[dev-dependencies]
serial_test.workspace = true
