[package]
name = "oxdock-buildtime-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
oxdock-core.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
tempfile.workspace = true

[dev-dependencies]
serial_test.workspace = true
