[workspace]
members = [
	"embed-recipe",
	"embed-recipe-dsl",
	"embed-recipe-macros",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
serde_json = "1.0.145"
tempfile = "3.23.0"
rust-embed = { version = "8.9.0", features = ["include-exclude"] }
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0", features = ["full"] }

# Internal crates
embed-recipe-dsl = { path = "embed-recipe-dsl", version = "0.1.0" }
embed-recipe-macros = { path = "embed-recipe-macros", version = "0.1.0" }
