[workspace]
members = [
    "oxdock-buildtime-macros",
    # Fixture crate used by the macros crate trybuild test to verify manifest-dir behavior.
    "oxdock-buildtime-macros/tests/fixtures/build_from_manifest",
    "oxdock-cli",
    "oxdock-core",
    "oxdock-fs",
]
default-members = ["oxdock-cli", "oxdock-core", "oxdock-buildtime-macros", "oxdock-fs"]
resolver = "2"

[workspace.package]
authors = ["Jeremy Harris <jeremy.harris@zenosmosis.com>"]
version = "0.1.0-alpha"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/jzombie/oxdock-rs"
publish = true

[workspace.dependencies]
anyhow = "1.0.100"
indoc = "2.0.7"
oxdock-buildtime-macros = { path = "oxdock-buildtime-macros", version = "0.1.0-alpha" }

# Internal crates
oxdock-core = { path = "oxdock-core", version = "0.1.0-alpha" }
oxdock-fs = { path = "oxdock-fs", version = "0.1.0-alpha" }
proc-macro2 = "1.0.103"
quote = "1.0.42"
rust-embed = { version = "8.9.0", features = ["include-exclude"] }
serial_test = "3.2.0"
syn = { version = "2.0", features = ["full"] }
tempfile = "3.23.0"
