[package]
name = "oxdock-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow.workspace = true
oxdock-buildtime-macros.workspace = true
oxdock-core.workspace = true
rust-embed.workspace = true
tempfile.workspace = true

[dev-dependencies]
indoc.workspace = true
